// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Frame_Type int32

const (
	Frame_VIDEO Frame_Type = 0
	Frame_AUDIO Frame_Type = 1
)

var Frame_Type_name = map[int32]string{
	0: "VIDEO",
	1: "AUDIO",
}

var Frame_Type_value = map[string]int32{
	"VIDEO": 0,
	"AUDIO": 1,
}

func (x Frame_Type) String() string {
	return proto.EnumName(Frame_Type_name, int32(x))
}

func (Frame_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1, 0}
}

type Timestamp struct {
	Pts                  uint64   `protobuf:"varint,1,opt,name=pts,proto3" json:"pts,omitempty"`
	Dts                  uint64   `protobuf:"varint,2,opt,name=dts,proto3" json:"dts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetPts() uint64 {
	if m != nil {
		return m.Pts
	}
	return 0
}

func (m *Timestamp) GetDts() uint64 {
	if m != nil {
		return m.Dts
	}
	return 0
}

type Frame struct {
	Type                 Frame_Type `protobuf:"varint,1,opt,name=type,proto3,enum=message.Frame_Type" json:"type,omitempty"`
	Timestamp            *Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionId            int32      `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Buffer               []byte     `protobuf:"bytes,4,opt,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetType() Frame_Type {
	if m != nil {
		return m.Type
	}
	return Frame_VIDEO
}

func (m *Frame) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Frame) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *Frame) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type Disconnected struct {
	SessionId            int32    `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disconnected) Reset()         { *m = Disconnected{} }
func (m *Disconnected) String() string { return proto.CompactTextString(m) }
func (*Disconnected) ProtoMessage()    {}
func (*Disconnected) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Disconnected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disconnected.Unmarshal(m, b)
}
func (m *Disconnected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disconnected.Marshal(b, m, deterministic)
}
func (m *Disconnected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disconnected.Merge(m, src)
}
func (m *Disconnected) XXX_Size() int {
	return xxx_messageInfo_Disconnected.Size(m)
}
func (m *Disconnected) XXX_DiscardUnknown() {
	xxx_messageInfo_Disconnected.DiscardUnknown(m)
}

var xxx_messageInfo_Disconnected proto.InternalMessageInfo

func (m *Disconnected) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func init() {
	proto.RegisterEnum("message.Frame_Type", Frame_Type_name, Frame_Type_value)
	proto.RegisterType((*Timestamp)(nil), "message.Timestamp")
	proto.RegisterType((*Frame)(nil), "message.Frame")
	proto.RegisterType((*Disconnected)(nil), "message.Disconnected")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xbb, 0x36, 0xa9, 0x64, 0x8c, 0x25, 0xac, 0x28, 0x41, 0x14, 0x42, 0x2e, 0xe6, 0x62,
	0x2a, 0x11, 0xbc, 0x78, 0x52, 0xa2, 0x90, 0x83, 0x14, 0x62, 0xf5, 0xe0, 0x45, 0xd2, 0xee, 0x54,
	0xf6, 0x90, 0x64, 0xc9, 0xac, 0x87, 0x3e, 0x99, 0xaf, 0x27, 0xd9, 0xa4, 0xd1, 0xf6, 0x36, 0xff,
	0x3f, 0x1f, 0xfb, 0x31, 0x0b, 0xc7, 0x25, 0x12, 0x15, 0x5f, 0x18, 0xab, 0xa6, 0xd6, 0x35, 0x3f,
	0xec, 0x63, 0x38, 0x03, 0x67, 0x21, 0x4b, 0x24, 0x5d, 0x94, 0x8a, 0x7b, 0x30, 0x56, 0x9a, 0x7c,
	0x16, 0xb0, 0xc8, 0xca, 0xdb, 0xb1, 0x6d, 0x84, 0x26, 0xff, 0xa0, 0x6b, 0x84, 0xa6, 0xf0, 0x87,
	0x81, 0xfd, 0xdc, 0x14, 0x25, 0xf2, 0x2b, 0xb0, 0xf4, 0x46, 0xa1, 0xc1, 0xa7, 0xc9, 0x49, 0xbc,
	0x35, 0x98, 0x6d, 0xbc, 0xd8, 0x28, 0xcc, 0x0d, 0xc0, 0x6f, 0xc0, 0xd1, 0x5b, 0x87, 0x79, 0xea,
	0x28, 0xe1, 0x03, 0x3d, 0xd8, 0xf3, 0x3f, 0x88, 0x5f, 0x02, 0x10, 0x12, 0xc9, 0xba, 0xfa, 0x94,
	0xc2, 0x1f, 0x07, 0x2c, 0xb2, 0x73, 0xa7, 0x6f, 0x32, 0xc1, 0xcf, 0x60, 0xb2, 0xfc, 0x5e, 0xaf,
	0xb1, 0xf1, 0xad, 0x80, 0x45, 0x6e, 0xde, 0xa7, 0xf0, 0x02, 0xac, 0x56, 0xcb, 0x1d, 0xb0, 0xdf,
	0xb3, 0xf4, 0x69, 0xee, 0x8d, 0xda, 0xf1, 0xe1, 0x2d, 0xcd, 0xe6, 0x1e, 0x0b, 0xaf, 0xc1, 0x4d,
	0x25, 0xad, 0xea, 0xaa, 0xc2, 0x95, 0x46, 0xb1, 0x27, 0x61, 0x7b, 0x92, 0x24, 0x05, 0x78, 0x41,
	0x21, 0x8b, 0xee, 0xd8, 0x3b, 0x70, 0x5e, 0xb1, 0x12, 0x5d, 0x98, 0xee, 0xde, 0x7a, 0x7e, 0x3a,
	0xe4, 0xff, 0x82, 0x70, 0x14, 0xb1, 0x47, 0xf7, 0x03, 0xe2, 0xd9, 0x7d, 0xbf, 0x5e, 0x4e, 0xcc,
	0xef, 0xdf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xb4, 0x33, 0x68, 0x8e, 0x01, 0x00, 0x00,
}
